# Generated by Django 5.0.1 on 2025-12-13 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narx (USD)')),
                ('airline', models.CharField(max_length=100, verbose_name='Aviakompaniya')),
                ('flight_duration_minutes', models.IntegerField(verbose_name='Davomiylik (daqiqa)')),
                ('departure_date', models.DateField(verbose_name='Uchish sanasi')),
                ('departure_time', models.TimeField(blank=True, null=True, verbose_name='Uchish vaqti')),
                ('arrival_time', models.TimeField(blank=True, null=True, verbose_name="Qo'nish vaqti")),
                ('is_roundtrip', models.BooleanField(default=False, verbose_name='Borib-qaytish')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='destinations.city', verbose_name='Qayerga')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='destinations.city', verbose_name='Qayerdan')),
            ],
            options={
                'verbose_name': 'Parvoz narxi',
                'verbose_name_plural': 'Parvoz narxlari',
                'ordering': ['price_usd'],
            },
        ),
        migrations.CreateModel(
            name='HotelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=200, verbose_name='Mehmonxona nomi')),
                ('stars', models.IntegerField(choices=[(1, '1 yulduz'), (2, '2 yulduz'), (3, '3 yulduz'), (4, '4 yulduz'), (5, '5 yulduz')], verbose_name='Yulduzlar')),
                ('price_per_night_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kechalik narx (USD)')),
                ('rating', models.DecimalField(decimal_places=1, default=8.0, max_digits=3, verbose_name='Reyting')),
                ('checkin_date', models.DateField(verbose_name='Kirish sanasi')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Rasm URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='destinations.city', verbose_name='Shahar')),
            ],
            options={
                'verbose_name': 'Mehmonxona narxi',
                'verbose_name_plural': 'Mehmonxona narxlari',
                'ordering': ['price_per_night_usd'],
            },
        ),
    ]
