# Generated by Django 5.0.1 on 2025-12-13 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField(verbose_name='Ketish sanasi')),
                ('return_date', models.DateField(verbose_name='Qaytish sanasi')),
                ('travelers', models.IntegerField(default=1, verbose_name="Yo'lovchilar soni")),
                ('include_transit', models.BooleanField(default=True, verbose_name="Tranzit qo'shish")),
                ('hotel_stars', models.IntegerField(default=3, verbose_name='Mehmonxona yulduzlari')),
                ('budget_max_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maksimal byudjet (USD)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_destinations', to='destinations.city', verbose_name='Qayerga')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_origins', to='destinations.city', verbose_name='Qayerdan')),
            ],
            options={
                'verbose_name': 'Sayohat qidiruvi',
                'verbose_name_plural': 'Sayohat qidiruvlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_type', models.CharField(choices=[('direct', "To'g'ridan-to'g'ri"), ('transit', 'Tranzit'), ('multi', 'Multi-city')], max_length=20, verbose_name="Yo'nalish turi")),
                ('cities_sequence', models.JSONField(default=list, verbose_name='Shaharlar ketma-ketligi')),
                ('total_flight_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jami parvoz narxi (USD)')),
                ('total_hotel_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jami mehmonxona narxi (USD)')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jami narx (USD)')),
                ('savings_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tejamkorlik (%)')),
                ('savings_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tejamkorlik (USD)')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='Tavsiya etiladi')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Ball')),
                ('details', models.JSONField(default=dict, verbose_name='Tafsilotlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='search.travelsearch', verbose_name='Qidiruv')),
            ],
            options={
                'verbose_name': "Yo'nalish varianti",
                'verbose_name_plural': "Yo'nalish variantlari",
                'ordering': ['total_cost'],
            },
        ),
    ]
