# Generated by Django 4.2.7 on 2025-12-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routevariant',
            name='route_type',
            field=models.CharField(choices=[('direct', "To'g'ridan-to'g'ri"), ('transit', 'Tranzit'), ('multi', 'Multi-city'), ('optimal_cheap', 'Optimal (arzon)'), ('optimal_fast', 'Optimal (tez)')], max_length=20, verbose_name="Yo'nalish turi"),
        ),
    ]
