# Generated by Django 5.0.1 on 2025-12-13 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi (English)')),
                ('name_uz', models.CharField(max_length=100, verbose_name="Nomi (O'zbekcha)")),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='ISO kod')),
                ('flag_emoji', models.CharField(max_length=10, verbose_name='Bayroq emoji')),
                ('currency', models.CharField(max_length=10, verbose_name='Valyuta')),
                ('visa_required_for_uz', models.BooleanField(default=False, verbose_name='Viza kerakmi')),
            ],
            options={
                'verbose_name': 'Mamlakat',
                'verbose_name_plural': 'Mamlakatlar',
                'ordering': ['name_uz'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi (English)')),
                ('name_uz', models.CharField(max_length=100, verbose_name="Nomi (O'zbekcha)")),
                ('iata_code', models.CharField(max_length=3, unique=True, verbose_name='IATA kodi')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Kenglik')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Uzunlik')),
                ('is_hub', models.BooleanField(default=False, verbose_name='Tranzit hub')),
                ('avg_hotel_price_usd', models.DecimalField(decimal_places=2, default=50.0, max_digits=10, verbose_name="O'rtacha mehmonxona narxi (USD)")),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='destinations.country', verbose_name='Mamlakat')),
            ],
            options={
                'verbose_name': 'Shahar',
                'verbose_name_plural': 'Shaharlar',
                'ordering': ['name_uz'],
            },
        ),
    ]
