# Generated by Django 5.0.1 on 2025-12-15 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="O'rtacha narx (USD)")),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Minimal narx (USD)')),
                ('popularity_score', models.IntegerField(default=0, verbose_name='Mashhurlik balli')),
                ('searches_count', models.IntegerField(default=0, verbose_name='Qidiruvlar soni')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='Rasm URL')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('best_season', models.CharField(blank=True, max_length=50, verbose_name='Eng yaxshi mavsum')),
                ('flight_duration_avg', models.IntegerField(default=0, verbose_name="O'rtacha parvoz davomiyligi (daqiqa)")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilanish')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popular_routes_to', to='destinations.city', verbose_name='Qayerga')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popular_routes_from', to='destinations.city', verbose_name='Qayerdan')),
            ],
            options={
                'verbose_name': "Mashhur yo'nalish",
                'verbose_name_plural': "Mashhur yo'nalishlar",
                'ordering': ['-popularity_score', '-searches_count'],
                'unique_together': {('origin', 'destination')},
            },
        ),
    ]
